spring:
  application:
    name: memorial_application
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${JDBC_DRIVER_SOURCE}
    url: ${DB_URL}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect


server:
  port:
    ${SERVER_PORT}


grpc:
  client:
    anime-server:
      address: ${GRPC_ANIME_SERVER_ADDRESS}
      negotiationType: "plaintext"



kafka:
  bootstrap-servers: ${KAFKA_SERVER}
  consumer:
    group-id: memorial
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer